### ISSUE TITLE
Roadmap!

### ISSUE THREAD

**Issue by Subwaytime** [Subwaytime/vite-aliases#1]
### Potential Features

- [ ] Add a Watcher (Currently if you add a new Folder into the base Structure, you gotta run vite again!)
- [ ] Deep Structuring (Allow subdirectories as aliases)

**Comment by Subwaytime** [comment]
### Needed Features

- [ ] Allow Leading and Trailing Slashes for Aliases (vite 1 and @rollup dynamic-import fix)
